FROM python:3.12

WORKDIR /api

COPY api/requirements* .

RUN python -m pip install -r requirements-dev.txt

COPY api .

RUN useradd -m container

RUN chown -R container:container /api

USER container

WORKDIR /api

CMD ["pytest"]