FROM python:3.12

WORKDIR /app

COPY api/requirements* .

RUN python -m pip install -r requirements-dev.txt

COPY api .

RUN useradd -m container

RUN chown -R container:container /app

USER container

WORKDIR /app

CMD ["pytest"]