name: Main pipeline
run-name: Running tests by @${{ github.actor }}


on:
  workflow_dispatch:
  push:

jobs:
  run-docker-unittests:
    env:
      IMAGE_NAME: ${{ github.repository }}-api-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - name: Build Docker test image
        run: |
          docker build \
          -t ${{ env.IMAGE_NAME }} \
          -f api/Dockerfiles/Dockerfile-test \
          .
      - name: Run api unit tests inside Docker
        run: |
          docker run --rm \
          -e TESTING=1 \
          ${{ env.IMAGE_NAME }}

  build-push-api-image:
    needs: run-docker-unittests
    if: ${{ github.ref_name == 'deployment' }}
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ github.repository }}-api:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - name: Login to dockerhub
        run: docker login -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t ${{ env.IMAGE_NAME }} -f api/Dockerfiles/Dockerfile .
      - name: Push to Dockerhub
        run: docker push ${{ env.IMAGE_NAME }}

