name: Tests for api
run-name: Running tests by @${{ github.actor }}


on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature*'
      - '*feature'
    paths:
      - 'api/**'

jobs:
  run-unittests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - name: Build Docker image
        run: |
          docker build \
          -t ${{ github.repository }}-api \
          -f Dockerfiles/Dockerfile-test \
          .
      - name: Run ${{ github.repository }}-api
        run: |
          docker run --rm \
          -e TESTING=1 \
          ${{ github.repository }}-api